INSERT INTO products (
  slug,
  name,
  category,
  description,
  detail,
  bullets,
  stat_label,
  stat_value,
  accent,
  is_featured,
  price,
  period,
  image,
  image_alt,
  href,
  display_order
) VALUES
(
  'commerce-os',
  'Commerce OS',
  'Ecommerce Operations',
  'A command center for inventory, orders, and customer signals with clear workflows for daily teams.',
  'Built for growing brands that need speed without operational noise, with a clean control surface for every critical flow.',
  ARRAY['Unified inventory view', 'Order health timeline', 'Automated stock alerts']::text[],
  'Processing time',
  '-34%',
  'product-accent-lilac',
  true,
  '₹1,99,000',
  '/month',
  '/assets/featured-commerce.svg',
  'Commerce Flow product preview',
  '/products/commerce-flow',
  1
),
(
  'pulse-mobile',
  'Pulse Mobile',
  'Field Team App',
  'A mobile workspace for field teams to update tasks, log visits, and sync progress in real time.',
  'Designed for low-friction usage in the real world with fast forms, offline support patterns, and clear completion states.',
  ARRAY['Offline-safe actions', 'Smart visit checklists', 'Instant status sync']::text[],
  'Task completion',
  '+27%',
  'product-accent-amber',
  true,
  '₹1,49,000',
  '/month',
  '/assets/featured-mobile.svg',
  'Pulse Mobile product preview',
  '/products/pulse-mobile',
  2
),
(
  'ops-dashboard',
  'Ops Dashboard',
  'Internal Web App',
  'A live performance dashboard for internal teams with role-specific insights and actionable reporting.',
  'Structured to help teams make faster decisions, not just read charts, with purposeful views and focused data density.',
  ARRAY['Role-based analytics', 'Live KPI boards', 'Cross-team drilldowns']::text[],
  'Decision cycle',
  '-41%',
  'product-accent-cyan',
  true,
  '₹1,74,000',
  '/month',
  '/assets/featured-analytics.svg',
  'Ops Atlas product preview',
  '/products/ops-atlas',
  3
),
(
  'studio-custom',
  'Studio Custom',
  'Custom Product Build',
  'A bespoke software product framework for teams that need unique workflows and flexible foundations.',
  'From MVP to scale-up, this model supports unusual product requirements while keeping the UI language elegant and coherent.',
  ARRAY['Modular architecture', 'Custom workflow engine', 'Future-ready scaling']::text[],
  'Delivery velocity',
  '+2.1x',
  'product-accent-rose',
  false,
  '₹2,90,000',
  '/project',
  '/assets/featured-custom.svg',
  'Studio Custom product preview',
  '/products/studio-custom',
  4
)
ON CONFLICT (slug) DO NOTHING;
